<?php

namespace ContainerWBlrOr0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QkU5qjrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qkU5qjr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qkU5qjr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eleve' => ['privates', '.errored..service_locator.qkU5qjr.App\\Entity\\Eleve', NULL, 'Cannot autowire service ".service_locator.qkU5qjr": it needs an instance of "App\\Entity\\Eleve" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'eleve' => 'App\\Entity\\Eleve',
        ]);
    }
}
