<?php

namespace ContainerWBlrOr0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IZd479Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._IZd479' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._IZd479'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trancheHoraire' => ['privates', '.errored..service_locator._IZd479.App\\Entity\\TrancheHoraire', NULL, 'Cannot autowire service ".service_locator._IZd479": it needs an instance of "App\\Entity\\TrancheHoraire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'trancheHoraire' => 'App\\Entity\\TrancheHoraire',
        ]);
    }
}
