<?php

namespace ContainerQgsE67F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmploiDuTempsSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\EmploiDuTempsSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\EmploiDuTempsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'EmploiDuTempsSubscriber.php';

        return $container->privates['App\\EventSubscriber\\EmploiDuTempsSubscriber'] = new \App\EventSubscriber\EmploiDuTempsSubscriber(($container->privates['App\\Repository\\TrancheHoraireRepository'] ?? $container->load('getTrancheHoraireRepositoryService')), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
