<?php

namespace ContainerQgsE67F;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTrancheHoraireService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._IZd479.App\Entity\TrancheHoraire' shared service.
     *
     * @return \App\Entity\TrancheHoraire
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator._IZd479": it needs an instance of "App\\Entity\\TrancheHoraire" but this type has been excluded in "config/services.yaml".');
    }
}
