<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Eleve extends \App\Entity\Eleve implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'classeActuelle' => [parent::class, 'classeActuelle', null],
        "\0".parent::class."\0".'dateDInscription' => [parent::class, 'dateDInscription', null],
        "\0".parent::class."\0".'dateDeNaissance' => [parent::class, 'dateDeNaissance', null],
        "\0".parent::class."\0".'ecoleDeProvenance' => [parent::class, 'ecoleDeProvenance', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'inscriptions' => [parent::class, 'inscriptions', null],
        "\0".parent::class."\0".'lieuDeNaissance' => [parent::class, 'lieuDeNaissance', null],
        "\0".parent::class."\0".'matricule' => [parent::class, 'matricule', null],
        "\0".parent::class."\0".'nationalite' => [parent::class, 'nationalite', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'parents' => [parent::class, 'parents', null],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null],
        "\0".parent::class."\0".'prenoms' => [parent::class, 'prenoms', null],
        "\0".parent::class."\0".'sexe' => [parent::class, 'sexe', null],
        'classeActuelle' => [parent::class, 'classeActuelle', null],
        'dateDInscription' => [parent::class, 'dateDInscription', null],
        'dateDeNaissance' => [parent::class, 'dateDeNaissance', null],
        'ecoleDeProvenance' => [parent::class, 'ecoleDeProvenance', null],
        'id' => [parent::class, 'id', null],
        'inscriptions' => [parent::class, 'inscriptions', null],
        'lieuDeNaissance' => [parent::class, 'lieuDeNaissance', null],
        'matricule' => [parent::class, 'matricule', null],
        'nationalite' => [parent::class, 'nationalite', null],
        'nom' => [parent::class, 'nom', null],
        'parents' => [parent::class, 'parents', null],
        'photo' => [parent::class, 'photo', null],
        'prenoms' => [parent::class, 'prenoms', null],
        'sexe' => [parent::class, 'sexe', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
