<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Personnel extends \App\Entity\Personnel implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'acteDeNaissance' => [parent::class, 'acteDeNaissance', null],
        "\0".parent::class."\0".'compteBancaire' => [parent::class, 'compteBancaire', null],
        "\0".parent::class."\0".'cv' => [parent::class, 'cv', null],
        "\0".parent::class."\0".'dateAjout' => [parent::class, 'dateAjout', null],
        "\0".parent::class."\0".'dateDeNaissance' => [parent::class, 'dateDeNaissance', null],
        "\0".parent::class."\0".'diplomesAcademiques' => [parent::class, 'diplomesAcademiques', null],
        "\0".parent::class."\0".'diplomesProfessionnels' => [parent::class, 'diplomesProfessionnels', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'matricule' => [parent::class, 'matricule', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'numeroCNSS' => [parent::class, 'numeroCNSS', null],
        "\0".parent::class."\0".'prenoms' => [parent::class, 'prenoms', null],
        "\0".parent::class."\0".'tranchesHoraires' => [parent::class, 'tranchesHoraires', null],
        'acteDeNaissance' => [parent::class, 'acteDeNaissance', null],
        'compteBancaire' => [parent::class, 'compteBancaire', null],
        'cv' => [parent::class, 'cv', null],
        'dateAjout' => [parent::class, 'dateAjout', null],
        'dateDeNaissance' => [parent::class, 'dateDeNaissance', null],
        'diplomesAcademiques' => [parent::class, 'diplomesAcademiques', null],
        'diplomesProfessionnels' => [parent::class, 'diplomesProfessionnels', null],
        'id' => [parent::class, 'id', null],
        'matricule' => [parent::class, 'matricule', null],
        'nom' => [parent::class, 'nom', null],
        'numeroCNSS' => [parent::class, 'numeroCNSS', null],
        'prenoms' => [parent::class, 'prenoms', null],
        'tranchesHoraires' => [parent::class, 'tranchesHoraires', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
