<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnneeScolaire extends \App\Entity\AnneeScolaire implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'active' => [parent::class, 'active', null],
        "\0".parent::class."\0".'classes' => [parent::class, 'classes', null],
        "\0".parent::class."\0".'debut' => [parent::class, 'debut', null],
        "\0".parent::class."\0".'designation' => [parent::class, 'designation', null],
        "\0".parent::class."\0".'fin' => [parent::class, 'fin', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'inscriptions' => [parent::class, 'inscriptions', null],
        'active' => [parent::class, 'active', null],
        'classes' => [parent::class, 'classes', null],
        'debut' => [parent::class, 'debut', null],
        'designation' => [parent::class, 'designation', null],
        'fin' => [parent::class, 'fin', null],
        'id' => [parent::class, 'id', null],
        'inscriptions' => [parent::class, 'inscriptions', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
