<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8Sx2BpP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8Sx2BpP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8Sx2BpP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8Sx2BpP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8Sx2BpP\App_KernelDevDebugContainer([
    'container.build_hash' => '8Sx2BpP',
    'container.build_id' => '6374ae42',
    'container.build_time' => 1724586851,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8Sx2BpP');
