<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCUF6Tyz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCUF6Tyz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCUF6Tyz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCUF6Tyz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCUF6Tyz\App_KernelDevDebugContainer([
    'container.build_hash' => 'CUF6Tyz',
    'container.build_id' => '22fcb0b3',
    'container.build_time' => 1722088378,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCUF6Tyz');
