<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQgsE67F\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQgsE67F/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQgsE67F.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQgsE67F\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQgsE67F\App_KernelDevDebugContainer([
    'container.build_hash' => 'QgsE67F',
    'container.build_id' => '1c8c541e',
    'container.build_time' => 1720598909,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQgsE67F');
